language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  #- "pypy-5.3.1"


allow_failures:
  - python: "3.7-dev"
  #- python: "pypy-5.3.1"

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python setup.py install
script:
  - pipenv run py.test
